# https://taskfile.dev

version: "3"

tasks:
  test:
    cmds:
      - go test -count=1 -race -v

  update/miniflac:
    cmds:
      - curl -o miniflac.h https://raw.githubusercontent.com/jprjr/miniflac/refs/heads/main/miniflac.h
    sources:
      - Taskfile.yml
    generates:
      - miniflac.h

  update/testdata:
    deps: [update/testdata/pcm]

  update/testdata/flac:
    cmds:
      - curl -o $TMPDIR/Sample_BeeMoved_96kHz24bit.flac.zip https://helpguide.sony.net/high-res/sample1/v1/data/Sample_BeeMoved_96kHz24bit.flac.zip # use $TMPDIR
      - unzip -o $TMPDIR/Sample_BeeMoved_96kHz24bit.flac.zip -d testdata
    status:
      - test -f testdata/Sample_BeeMoved_96kHz24bit.flac

  update/testdata/pcm:
    deps: [update/testdata/flac]
    cmds:
      - go test -count=1 -write-golden=true
    sources:
      - testdata/Sample_BeeMoved_96kHz24bit.flac
    generates:
      - testdata/Sample_BeeMoved_96kHz24bit.pcm

  play/testdata/pcm:
    cmds:
      - ffplay -autoexit -f s32le -ar 96k -ch_layout stereo testdata/Sample_BeeMoved_96kHz24bit.pcm

  run/docker:
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .
      - "cat ./testdata/Sample_BeeMoved_96kHz24bit.flac | docker run --rm -i {{.DOCKER_IMAGE}} | ffplay -autoexit -i pipe:"
    vars:
      DOCKER_IMAGE: cowork-ai/go-miniflac
